variables:
  CI_IMAGE_TAG: 'plain'

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v5/test.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v5/coverage.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v5/documentation.yml'


# basic tests

test:v1.0:
  extends: .test:v1.0

test:v1.1:
  extends: .test:v1.1

test:v1.2:
  extends: .test:v1.2

test:v1.3:
  extends: .test:v1.3
  allow_failure: true

test:dev:
  extends: .test:dev
  allow_failure: true


# special tests

test:dev:llvm8:
  extends: .test:dev
  image: ubuntu:18.04
  before_script:
    - apt update
    - apt install -y git build-essential libatomic1 python gfortran perl wget m4 cmake pkg-config
    - git clone https://github.com/JuliaLang/julia
    - make -C julia -j$(nproc) install LLVM_VER=8.0.0 USE_BINARYBUILDER_LLVM=0
    - ln -s $(pwd)/julia/julia /usr/bin/julia
    - julia -e 'using InteractiveUtils;
                versioninfo()'

test:dev:llvm9:
  extends: .test:dev
  image: ubuntu:18.04
  before_script:
    - apt update
    - apt install -y git build-essential libatomic1 python gfortran perl wget m4 cmake pkg-config
    - git clone https://github.com/JuliaLang/julia
    - make -C julia -j$(nproc) install LLVM_VER=9.0.0rc6 USE_BINARYBUILDER_LLVM=0
    - ln -s $(pwd)/julia/julia /usr/bin/julia
    - julia -e 'using InteractiveUtils;
                versioninfo()'
