variables:
  CI_IMAGE_TAG: 'plain'

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v1/common.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v1/test_v0.7.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v1/test_v1.0.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v1/test_v1.1.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v1/test_dev.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v1/coverage_v1.1.yml'

test:v0.7:
  only:
    - master
    - staging
    - trying

test:v1.0:
  only:
    - staging
    - trying
    - master

test:v1.1:
  only:
    - staging
    - trying
    - master

test:dev:
  only:
    - master
    - staging
    - trying

coverage:
  only:
    - master
    - staging
    - trying
