language: julia

os:
  - linux
  - osx

julia:
  - nightly

notifications:
  email: false

env:
  global:
    - DOCUMENTER_DEBUG=true

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("LLVM")); include(joinpath("docs", "make.jl"))'
