language: julia

os:
  - linux
  - osx

julia:
  - nightly

notifications:
  email: false

env:
  global:
    - DOCUMENTER_DEBUG=true

after_success:
  - julia -e 'cd(Pkg.dir("LLVM")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("LLVM")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
