language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - nightly

matrix:
  allow_failures:
  - julia: nightly
    os: osx

branches:
  only:
    - staging
    - trying

notifications:
  email: false
