language: julia
sudo: required
dist: trusty
notifications:
  email: false

addons_shortcuts:
  addons_llvm39linux: &llvm39linux
    apt:
      # https://github.com/travis-ci/apt-source-whitelist/issues/300
      sources: [ubuntu-toolchain-r-test, llvm-toolchain-precise-3.9]
      packages: [llvm-3.9]
  addons_llvm40linux: &llvm40linux
    apt:
      # https://github.com/travis-ci/apt-package-whitelist/issues/3296
      # https://github.com/travis-ci/apt-package-whitelist/pull/3297
      sources: [ubuntu-toolchain-r-test, llvm-toolchain-precise]
      packages: [llvm-4.0]

# NOTE: Travis does not allow applying a global (eg. julia/os array) to a matrix,
#       so construct it manually
matrix:
  include:
    # LLVM 3.9 on Linux
    - os: linux
      env: LLVM_VERSION=3.9
      julia: 0.5
      # addons: *llvm39linux
      before_install:
      - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main' -y
      - sudo apt-get update -q
      - sudo apt-get remove llvm -y
      - sudo apt-get install llvm-3.9 -y
    - os: linux
      env: LLVM_VERSION=3.9
      julia: nightly
      # addons: *llvm39linux
      before_install:
      - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main' -y
      - sudo apt-get update -q
      - sudo apt-get remove llvm -y
      - sudo apt-get install llvm-3.9 -y
    # LLVM 3.9 on Linux, DEBUG mode
    - os: linux
      env:
        - LLVM_VERSION=3.9
        - DEBUG=1
      julia: 0.5
      # addons: *llvm39linux
      before_install:
      - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main' -y
      - sudo apt-get update -q
      - sudo apt-get remove llvm -y
      - sudo apt-get install llvm-3.9 -y
    - os: linux
      env:
        - LLVM_VERSION=3.9
        - DEBUG=1
      julia: nightly
      # addons: *llvm39linux
      before_install:
      - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main' -y
      - sudo apt-get update -q
      - sudo apt-get remove llvm -y
      - sudo apt-get install llvm-3.9 -y
    # LLVM 4.0 on Linux
    - os: linux
      env: LLVM_VERSION=4.0
      julia: 0.5
      # addons: *llvm40linux
      before_install:
      - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main' -y
      - sudo apt-get update -q
      - sudo apt-get remove llvm -y
      - sudo apt-get install llvm-4.0 -y
    - os: linux
      env: LLVM_VERSION=4.0
      julia: nightly
      # addons: *llvm40linux
      before_install:
      - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main' -y
      - sudo apt-get update -q
      - sudo apt-get remove llvm -y
      - sudo apt-get install llvm-4.0 -y
    # LLVM 4.0 on Linux, DEBUG mode
    - os: linux
      env:
        - LLVM_VERSION=4.0
        - DEBUG=1
      julia: 0.5
      # addons: *llvm40linux
      before_install:
      - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main' -y
      - sudo apt-get update -q
      - sudo apt-get remove llvm -y
      - sudo apt-get install llvm-4.0 -y
    - os: linux
      env:
        - LLVM_VERSION=4.0
        - DEBUG=1
      julia: nightly
      # addons: *llvm40linux
      before_install:
      - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main' -y
      - sudo apt-get update -q
      - sudo apt-get remove llvm -y
      - sudo apt-get install llvm-4.0 -y
    # # LLVM 3.9 on macOS
    # - os: osx
    #   env: LLVM_VERSION=3.9
    #   julia: 0.5
    #   before_install:
    #   - wget http://llvm.org/releases/3.9.0/clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz
    #   - tar -xvf clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz
    #   - export PATH=$PATH:$PWD/clang+llvm-3.9.0-x86_64-apple-darwin/bin/
    # - os: osx
    #   env: LLVM_VERSION=3.9
    #   julia: nightly
    #   before_install:
    #   - wget http://llvm.org/releases/3.9.0/clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz
    #   - tar -xvf clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz
    #   - export PATH=$PATH:$PWD/clang+llvm-3.9.0-x86_64-apple-darwin/bin/
    # # LLVM 3.9 on macOS, DEBUG mode
    # - os: osx
    #   env:
    #     - LLVM_VERSION=3.9
    #     - DEBUG=1
    #   julia: 0.5
    #   before_install:
    #   - wget http://llvm.org/releases/3.9.0/clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz
    #   - tar -xvf clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz
    #   - export PATH=$PATH:$PWD/clang+llvm-3.9.0-x86_64-apple-darwin/bin/
    # - os: osx
    #   env:
    #     - LLVM_VERSION=3.9
    #     - DEBUG=1
    #   julia: nightly
    #   before_install:
    #   - wget http://llvm.org/releases/3.9.0/clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz
    #   - tar -xvf clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz
    #   - export PATH=$PATH:$PWD/clang+llvm-3.9.0-x86_64-apple-darwin/bin/

after_success:
 - julia -e 'cd(Pkg.dir("LLVM")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
