branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
  matrix:
    - JULIA: 0.7-32bit
    - JULIA: 0.7-64bit
    - JULIA: nightly-32bit
    - JULIA: nightly-64bit

install:
  - powershell .\appveyor.ps1

build_script:
  - C:\julia\bin\julia -e "using InteractiveUtils;
                           versioninfo();
                           using Pkg;
                           Pkg.instantiate();
                           Pkg.build()"

test_script:
  - C:\julia\bin\julia -e "using Pkg;
                           Pkg.test()"
